### ISSUE TITLE
Doesn't work on the latest Spotify update.

### ISSUE THREAD

**Issue by marchingon12** [abba23/spotify-adblock-linux#75]
As the title says, spotify-adblock-linux is not working on the latest update (v.1.1.42.622-1). Visual ads as well as audio ads have been showing up as of late.

I just wanted to confirm if this only applies to me, because it was working on the previous version of Spotify. If you are aware of this issue working on it, I apologize in advance for not seeing it. I appreciate your work a lot.

Latest Spotify package: https://aur.archlinux.org/packages/spotify/
OS: Manjaro Linux 20.1
spotify-adblock-linux version: cloned from Github and pulled recently.

**Comment by abba23** [comment]
>spotify-adblock-linux version: cloned from Github and pulled recently

How recently? It should be working with the latest commit. See https://github.com/abba23/spotify-adblock-linux/issues/65.

**Comment by marchingon12** [comment]
I will try three more times if it fails repeatedly 👍🏽 . I shall attach screen shots or a screen recording in my next comment . Please bare with me for now, as I'm backing up some work.

**Comment by marchingon12** [comment]
I confirm that it still isn't working for me after a few tries, git pulls, rebuilding and installing. 

![image](https://user-images.githubusercontent.com/41235480/95027446-07bbd000-0688-11eb-8bfc-e34fd46ed81a.png)
![image](https://user-images.githubusercontent.com/41235480/95027480-55d0d380-0688-11eb-873f-5bb93b07055e.png)
![image](https://user-images.githubusercontent.com/41235480/95027494-739e3880-0688-11eb-8da1-e9ed10ca3ba2.png)

**Comment by abba23** [comment]
Please try launching it from a terminal and post the output.

**Comment by marchingon12** [comment]
![image](https://user-images.githubusercontent.com/41235480/95027649-bdd3e980-0689-11eb-8efd-c8f062cfa6d5.png)

**Comment by abba23** [comment]
Looks like the same issue as https://github.com/abba23/spotify-adblock-linux/issues/41.

**Comment by marchingon12** [comment]
Indeed this was the case! I'm not sure why updating Spotify made it not work, but I'm glad it's working! Thanks for your time.
